import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
print("array is",a)
sum=np.sum(a)
print("sum",sum)
average=np.mean(a)
print("average of array",average)
minimum=np.min(a)
print("minimum of array",minimum)
maximum=np.max(a)
print("maximum of array",maximum)
imin=np.argmin(a)
print("index",imin)
imax=np.argmax(a)
print("index of maximun",imax)
mid=np.median(a)
print("middle value",mid)
stdv=np.std(a)
print("standard varience",stdv)
vari=np.var(a)
print("varience",vari)